Coastguard to master
rreinecke/global-gradient-based-groundwater-model pull request #44
Opened 2024-06-17 12:32 UTC by daniel-v-k

2024-06-17 15:11 UTC, rreinecke commented on cmake/llvm-gcov.sh
can this be removed?

2024-06-17 15:11 UTC, rreinecke commented on lib/Eigen/src/Core/Assign_MKL.h
Can this and the other Eigen files be removed?

2024-06-17 15:12 UTC, rreinecke commented on lib/Eigen/src/Core/Assign_MKL.h
@daniel-v-k

2024-06-17 15:19 UTC, rreinecke requested changes
Likely some files can be removed. @daniel-v-k

2024-06-19 14:05 UTC, daniel-v-k commented on lib/Eigen/src/Core/Assign_MKL.h
Very likely yes. Will check if everything still works as expected after this merge.

2024-06-19 16:27 UTC, rreinecke approved these changes

2024-06-19 16:27 UTC, merged